# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-09 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='tracking_pixel_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
