# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-09 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0002_email_tracking_pixel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_emails', to='email_sender.Email')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_emails', to='email_sender.Subscriber')),
            ],
        ),
    ]
