# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-09 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0003_emailopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailopen',
            name='opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailopen',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
