# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-09 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0004_auto_20230609_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='tracking_pixel_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
