# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-09 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0005_auto_20230609_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='scheduled_time',
        ),
    ]
