# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-09 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0006_remove_email_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='schedule_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
