# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-09 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0007_email_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='schedule_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
