# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-09 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0008_auto_20230609_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='emails', to='email_sender.Subscriber'),
        ),
    ]
