# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-09 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0009_auto_20230609_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailopen',
            name='subscriber',
        ),
    ]
