# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-10 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0010_remove_emailopen_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailopen',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opened_emails', to='email_sender.Subscriber'),
        ),
    ]
