# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-10 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0012_auto_20230610_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='tracking_pixel_id',
        ),
        migrations.AddField(
            model_name='emailopen',
            name='tracking_pixel_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
